name: "Deploy to AWS EC2"

on: workflow_dispatch

jobs:
  ci-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4

      - name: install dependencies
        run: npm install

      - name: test code
        run: npm test

      - name: build code
        run: npm run build

      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "react-build"
          path: ./build


  cd-job:
    runs-on: self-hosted
    needs: ci-job
    if: success()
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: "react-build"
          path: ./build

      - name: deploy to aws
        run: serve -s build & exit 0
