name: "Deploy to AWS EC2"

on: workflow_dispatch

jobs:
  ci-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4

      - name: install dependencies
        run: npm install

      - name: test code
        run: npm test

      - name: build code
        run: npm run build

      - name: deploy to aws
        run: |
          sudo mkdir -p /var/www/html
          sudo rm -rf /var/www/html/*
          sudo cp -r /home/ubuntu/actions-runner/_work/ci_cd_aws/ci_cd_aws/build/* /var/www/html/
          pm2 start index.html



# NEED THIS KIND OF CONFIGURATION FOR DEPLOYING INTO EC2 OF AWS
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1  # Update to your AWS region

      # - name: Deploy to EC2
      #   run: |
      #     ssh -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
      #       sudo rm -rf /var/www/html/*
      #       sudo cp -r /github/workspace/build/* /var/www/html/
      #       sudo systemctl restart nginx
      #     EOF